services:
  frontend:
    build:
      context: ./frontend
    container_name: stock-management-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  
  db:
      image: postgres:15
      environment:
        POSTGRES_USER: lucky
        POSTGRES_PASSWORD: lucky
        POSTGRES_DB: inventory_db
      volumes:
        - db-data:/var/lib/postgresql/data
      ports:
        - 5432:5432

volumes:
  db-data:
